classDiagram
 
    class Meetup {
        +string slug  %% PK 
        +string meetup_slug
        +string group
        +string subgroup
        +string emoji
        +string event_url

    }
    
    class Pike13Service {
        +string id  %% PK
        +string name
        +string type
        +text description
        +string description_short
        +text instructions
        +string category_name
        +int category_id
        +string category_slug
        +string price_string
        +integer scheduled_events_count
    }
    
    class P13Location {
        +string id 
        +string code  %% PK
        +string name
        +string address
        +float latitude
        +float longitude
        +string phone
        +text description
        +string slug
        +int position
        +datetime hidden_at
        +string formatted_address
        +string street_address
        +string street_address2
        +string city
        +string state_code
        +string postal_code
        +string country_code
        +string timezone_friendly
        +string timezone
        +string type
    }